#!/usr/bin/env bash
# =============================================================================
# Redfish Fleet Monitor — Central Server Deployment Script
# =============================================================================
# Run this on the Central Server machine (Ubuntu 22.04+ / Debian 12+).
#
# Prerequisites:
#   - Static IP configured at the OS level
#   - DNS A record pointing your domain to the static IP
#   - Docker and Docker Compose installed
#
# Usage:
#   chmod +x setup-central-server.sh
#   sudo ./setup-central-server.sh
# =============================================================================

set -euo pipefail

DOMAIN="${1:-}"

if [ -z "$DOMAIN" ]; then
    echo "Usage: sudo ./setup-central-server.sh <domain>"
    echo "Example: sudo ./setup-central-server.sh monitor.company.com"
    exit 1
fi

echo "═══════════════════════════════════════════════════════"
echo "  Redfish Fleet Monitor — Central Server Setup"
echo "  Domain: $DOMAIN"
echo "═══════════════════════════════════════════════════════"

# ── 1. Install Nginx ─────────────────────────────────────────────────────────
echo "\n[1/5] Installing Nginx..."
apt-get update -qq
apt-get install -y -qq nginx certbot python3-certbot-nginx

# ── 2. Configure Nginx ───────────────────────────────────────────────────────
echo "\n[2/5] Configuring Nginx reverse proxy..."
NGINX_CONF="/etc/nginx/sites-available/redfish-monitor"

cat > "$NGINX_CONF" <<NGINX_EOF
# Redfish Fleet Monitor — Auto-generated by setup-central-server.sh
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 10s;
    }

    location /socket.io/ {
        proxy_pass http://127.0.0.1:5000/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400s;
    }
}
NGINX_EOF

ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/redfish-monitor
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx
echo "  ✅ Nginx configured for $DOMAIN"

# ── 3. TLS Certificate ──────────────────────────────────────────────────────
echo "\n[3/5] Obtaining TLS certificate..."
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --register-unsafely-without-email || {
    echo "  ⚠️  Certbot failed. You can run manually later:"
    echo "     sudo certbot --nginx -d $DOMAIN"
}

# ── 4. Firewall ──────────────────────────────────────────────────────────────
echo "\n[4/5] Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw allow 22/tcp   comment "SSH"      2>/dev/null || true
    ufw allow 80/tcp   comment "HTTP"     2>/dev/null || true
    ufw allow 443/tcp  comment "HTTPS"    2>/dev/null || true
    ufw deny 5000/tcp  comment "Block direct Flask" 2>/dev/null || true
    ufw deny 5432/tcp  comment "Block direct PostgreSQL" 2>/dev/null || true
    ufw --force enable 2>/dev/null || true
    echo "  ✅ UFW firewall configured"
else
    echo "  ⚠️  UFW not installed. Configure your firewall manually:"
    echo "     Allow: 22 (SSH), 80 (HTTP), 443 (HTTPS)"
    echo "     Block: 5000, 5432"
fi

# ── 5. Generate enrollment key ──────────────────────────────────────────────
echo "\n[5/5] Generating enrollment key..."
ENROLLMENT_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
ENROLLMENT_HASH=$(python3 -c "import hashlib, sys; print(hashlib.sha256(sys.argv[1].encode()).hexdigest())" "$ENROLLMENT_KEY")

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  ✅ Central Server setup complete!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  Domain:    https://$DOMAIN"
echo "  Nginx:     configured + TLS"
echo "  Firewall:  ports 80, 443 open"
echo ""
echo "  ┌─────────────────────────────────────────────────────┐"
echo "  │  ENROLLMENT KEY (share with customers):             │"
echo "  │  $ENROLLMENT_KEY  │"
echo "  └─────────────────────────────────────────────────────┘"
echo ""
echo "  Add this to backend/.env:"
echo "  ENROLLMENT_KEY_HASH=$ENROLLMENT_HASH"
echo ""
echo "  Next steps:"
echo "  1. Add ENROLLMENT_KEY_HASH to backend/.env"
echo "  2. cd /path/to/project && docker compose up -d"
echo "  3. Share the enrollment key with customers"
echo ""
