"""add device_type to servers

Revision ID: 870c5915b961
Revises: a2720e8743ce
Create Date: 2026-08-22 11:16:52.930216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870c5915b961'
down_revision = 'a2720e8743ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(length=64), server_default='server', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###
