"""initial schema

Revision ID: a2720e8743ce
Revises: 
Create Date: 2026-08-05 12:42:25.568318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a2720e8743ce'
down_revision = None
branch_labels = None
depends_on = None


def _uuid_col():
    """Return the right UUID column type for the current dialect."""
    return postgresql.UUID(as_uuid=True)


def _json_col():
    """Return JSONB on PostgreSQL, JSON otherwise."""
    return postgresql.JSONB()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agents',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('site_id', _uuid_col(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('health_status', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('servers',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('service_tag', sa.String(length=128), nullable=True),
    sa.Column('asset_tag', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=128), nullable=True),
    sa.Column('part_number', sa.String(length=128), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_location', sa.String(length=255), nullable=True),
    sa.Column('maintenance_records', sa.Text(), nullable=True),
    sa.Column('management_protocol', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('site_id', _uuid_col(), nullable=True),
    sa.Column('agent_id', _uuid_col(), nullable=True),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.Enum('UNKNOWN', 'CONNECTED', 'UNREACHABLE', 'AUTH_FAILED', name='connection_status_enum'), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('power_state', sa.String(length=32), nullable=True),
    sa.Column('last_poll_attempt', sa.DateTime(), nullable=True),
    sa.Column('last_successful_poll', sa.DateTime(), nullable=True),
    sa.Column('last_poll_error', sa.Text(), nullable=True),
    sa.Column('supports_event_service', sa.Boolean(), nullable=True),
    sa.Column('redfish_service_root', _json_col(), nullable=True),
    sa.Column('redfish_system_uri', sa.String(length=512), nullable=True),
    sa.Column('redfish_chassis_uri', sa.String(length=512), nullable=True),
    sa.Column('redfish_manager_uri', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('alerts',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('server_id', _uuid_col(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_property', sa.String(length=512), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('first_occurred_at', sa.DateTime(), nullable=True),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_server_id'), ['server_id'], unique=False)

    op.create_table('components',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('server_id', _uuid_col(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('odata_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('health', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('raw_json', _json_col(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'category', 'odata_id', name='uq_component_identity')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_server_id'), ['server_id'], unique=False)

    op.create_table('log_entries',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('server_id', _uuid_col(), nullable=False),
    sa.Column('log_service', sa.String(length=255), nullable=True),
    sa.Column('entry_id', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('sensor_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', _json_col(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'log_service', 'entry_id', name='uq_log_entry')
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_server_id'), ['server_id'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', _uuid_col(), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='operation_status_enum'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_path', sa.Text(), nullable=True),
    sa.Column('result_filename', sa.String(length=512), nullable=True),
    sa.Column('result_content_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_status'), ['status'], unique=False)

    op.create_table('redfish_sessions',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('server_id', _uuid_col(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('session_uri', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redfish_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redfish_sessions_server_id'), ['server_id'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', _uuid_col(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_readings_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_readings_server_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_metric'))

    op.drop_table('sensor_readings')
    with op.batch_alter_table('redfish_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redfish_sessions_server_id'))

    op.drop_table('redfish_sessions')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_status'))
        batch_op.drop_index(batch_op.f('ix_operations_server_id'))
        batch_op.drop_index(batch_op.f('ix_operations_operation_type'))

    op.drop_table('operations')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_server_id'))
        batch_op.drop_index(batch_op.f('ix_log_entries_created_at'))

    op.drop_table('log_entries')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_server_id'))
        batch_op.drop_index(batch_op.f('ix_components_category'))

    op.drop_table('components')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_server_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_resolved'))
        batch_op.drop_index(batch_op.f('ix_alerts_dedupe_key'))

    op.drop_table('alerts')
    op.drop_table('servers')
    op.drop_table('agents')
    op.drop_table('sites')
    # ### end Alembic commands ###
